root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app/cloud ./cmd/cloud/main.go && ls ./tmp/app"
bin = "tmp/app"

full_bin = "chmod +x ./tmp/app/cloud && ./tmp/app/cloud"
log = "air_errors.log"

include_ext = ["go", "yml", "html"]
exclude_dir = ["tmp"]

delay = 1000

[log]
time = true

[misc]
clean_on_exit = true